#pragma once
#include "compiler.h"
#include "uintN_t.h"

// normal LEDs
DECL_OUTPUT(uint1_t, LEDR_N)
GLOBAL_OUT_WIRE_CONNECT(uint1_t, LEDR_N, LED1)

DECL_OUTPUT(uint1_t, LEDG_N)
GLOBAL_OUT_WIRE_CONNECT(uint1_t, LEDG_N, LED2)

// RGB LED
DECL_OUTPUT(uint1_t, LED_RED_N)
GLOBAL_OUT_WIRE_CONNECT(uint1_t, LED_RED_N, LED_RGB_R_N)

DECL_OUTPUT(uint1_t, LED_GRN_N)
GLOBAL_OUT_WIRE_CONNECT(uint1_t, LED_GRN_N, LED_RGB_G_N )

DECL_OUTPUT(uint1_t, LED_BLU_N)
GLOBAL_OUT_WIRE_CONNECT(uint1_t, LED_BLU_N, LED_RGB_B_N )
